### ISSUE TITLE
generator-goatstack does not installed on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by CodebitsDesign** [projectSHAI/GOATstack#4]
OS: Elementary OS Loki 4.0 64bit (based Ubuntu 16.04.2 LTS)
$ node -v
v7.8.0

$ sudo yarn global add generator-goatstack
yarn global v0.22.0
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning undefined has no binaries
warning No license field

**Comment by projectSHAI** [comment]
Good evening. 

Fortunately this is not an OS issue. The npm version of the generator is currently out of date.

Unfortunately my partner is the only author on npm for the generator, I will ask him to give me access; once he does I will update the npm version.

For now I would recommend using the github repository by cloning, and then doing an npm link. This version works well, I also use 16.04.2, and can attest that it works as expected.

go to this repo: https://github.com/JCThomas4214/GOAT-yeoman

Then do the following:
1) clone `git clone https://github.com/JCThomas4214/GOAT-yeoman`
2) in terminal change directories to the project folder.
3) make a link so you can use it as intended `npm link`

Once you do the above you can use `yo goatstack` commands as intended.

On a side note I am currently working on implementing Angular Universal into the generator, in case you are interested in server side rendering.

edit: Universal has been implemented.

**Comment by ghost** [comment]
This issue is over a month old...any update?

**Comment by projectSHAI** [comment]
The npm repository has been updated. This issue should not occur anymore.

Cheers!
