### ISSUE TITLE
Unable to install with Yarn or NPM succesfully

### ISSUE THREAD

**Issue by RemeJuan** [projectSHAI/GOATstack#5]
I just tried to install the stack and when using yarn I get the following.

```
$ yarn global add generator-goatstack
yarn global v0.22.0
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning undefined has no binaries
warning No license field
Done in 9.60s.
```

Using npm works, however all it creates is the folder with the package, license and readme as well as installing the node modules, but from there yeoman does not detect it as a generator, it is not even in the list when simply trying `yo`

**Comment by projectSHAI** [comment]
Good evening,

I am sorry for the confusion. My partner is the one who maintains the npm version of the generator. I will ask him to give me access to update this. For now please follow the solution in issue #4

**Comment by RemeJuan** [comment]
Thanks @projectSHAI, all sorted.

**Comment by projectSHAI** [comment]
Sweet! 

Also, good news @RemeJuan I just finished implementing server side rendering in case you wish to use that.

**Comment by RemeJuan** [comment]
@projectSHAI, I really need to look into SSR one day, been available for a few other frameworks already and just never bothered. This will once again be one of those cases, testing out GOAT mostly for the A4, but also for an upcoming project, need to play around with angulars new form schema's so I am literally spinning up an A4 app to write a form, a single solitary form.
