### ISSUE TITLE
query.on is not a fuction

### ISSUE THREAD

**Issue by nicoabbiuso** [projectSHAI/GOATstack#7]
I work with node, express and postrgres.
I have next index.js:

var express = require('express');
var router = express.Router();

var pg = require('pg');
var conString  =  "postgres://postgres:pass@localhost/name_bd";
var coffee_query = "SELECT * FROM tabla";

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });

});

/* GET Postgres JSON data */
router.get('/data', function (req, res) {
	
	
  var client = new pg.Client(conString);

	  client.connect();
	var query = client.query(coffee_query);
  
 
  query.on("row", function (row, result) {
    result.addRow(row);
  });
  
  
  query.on("end", function (result) {
    res.json(result.rows[0].row_to_json);
    res.end();
  });

  query.on('error', function(err) {
  console.log('Query error: ' + err);
});

});

module.exports = router;

but i see the next error: "query.on is not a function".
I tried whit other versions but appear new's error.

How i sollution this problem?

Thanks.

**Comment by projectSHAI** [comment]
This is an importing issue with pg which is independent from GOATstack.

However, I looked at the docs they provided and it seems like they import their query object as follows:

    const Query = require('pg').Query
    const query = new Query('select $1::text as name', ['brianc'])

    const result = client.query(query)

    assert(query === result) // true

    query.on('row', (row) => {
      console.log('row!', row) // { name: 'brianc' }
    })
    query.on('end', () => {
      console.log('query done')
    })
    query.on('error', (err) => {
      console.error(err.stack)
    })

Refactor your logic to replicate this and I'm confident it'll work.

You can read more about proper implementation here: [pg docs](https://node-postgres.com/api/client)

> Note: we use sequelize, which is sql database agnostic, making it trivial to migrate from one sql database to another. I suggest you look at sequelize to deal with your postgres APIs it'll be more flexible for future changes.
